services:
  # front:
  #   build: ./front
  #   ports:
  #     - '${NEXT_PORT}:${NEXT_PORT}'
  #   depends_on:
  #     - api

  # api:
  #   build: ./back/api
  #   ports:
  #     - '${API_PORT}:${API_PORT}'
  #   environment:
  #     - API_PORT=${API_PORT}
  #     - API_HOST=${API_HOST}
  # depends_on: -db

  db:
    image: postgres:16-alpine
    container_name: sample-db
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db:
