version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  # redis:
  #   image: redis:8.0.3-alpine
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    # depends_on:
    #   - postgres
    #   - redis

  # socket:
  #   build:
  #     context: .
  #     dockerfile: apps/socket/Dockerfile
  #   ports:
  #     - "${SOCKET_PORT}:${SOCKET_PORT}"
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - SOCKET_HOST=${SOCKET_HOST}
  #     - REDIS_URL=${REDIS_URL}
  #   depends_on:
  #     - postgres
  #     - redis

volumes:
  postgres:
  redis_data:
