services:
  db:
    image: postgres:16-alpine
    container_name: sample-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
  redis:
    image: redis:8.0.3-alpine
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  db:
  redis_data:
